name: vodafone
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.4
  flutter_feather_icons:
  google_fonts: ^3.0.1
  smooth_page_indicator: ^1.0.0+2
  pinput: ^2.2.12
  flutter_native_splash: ^2.2.8
  ionicons:
  get: ^4.6.5
  shared_preferences:
  get_storage:

flutter_native_splash:
  image: assets/splash.png
  color: "#e60000"
  image_dark: assets/splash.png
  color_dark: "#282c34"
  android_12:
    image: assets/splash.png
    color: "#e60000"
    image_dark: assets/splash.png
    color_dark: "#282c34"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.10.0
flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  background_color: "#ffffff"

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
