name: vodafone
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  convex_bottom_bar: ^3.0.0
  lottie: ^1.4.1
  flutter_svg: ^1.1.4
  percent_indicator: ^4.2.2
  flutter_feather_icons:
  google_fonts: ^3.0.1
  smooth_page_indicator: ^1.0.0+2
  pinput: ^2.2.12
  flutter_native_splash: ^2.2.8
  ionicons:

flutter_native_splash:
  image: assets/vodafone_logo.png
  color: "#e60000"
  android_12:
    image: assets/vodafone_logo.png
    color: "#e60000"
    icon_background_color: "#ffffff"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
